import 'package:flutter/material.dart';

class ColorConstants {
  static const Color primaryColor = Color(0xFFf3ebfb),
      secondaryColor = Color(0xfff4f2f8),
      buttonColor = Color(0xffccc4d4),
      circleBgColor = Color(0xfff8e2aa),
      dialPadBgColor = Color(0xfffdf0c5),
      whiteColor = Colors.white,
      blackColor = Colors.black,
      redColor = Colors.red,
      greyColor = Color(0xff9E9E9E),
      lightGreyColor = Color(0xffDEDEDE),
      shadowColor = Color(0xffD6D6D6),
      bottomNavBarSelectedColor = Color(0xff0D73CF),
      bottomNavBarUnselectedColor = Color(0xffCACACA),
      dividerColor = Color(0xff707070),
      unselectedLabelColor = Color(0xff777777),
      searchFieldTextColor = Color(0xFF848484),
      greenColor = Color(0xff2AB889),
      lightGreyTextColor = Color(0xFFA4A4A4),
      textFieldIconColor = Color(0xFFA5A5A5),
      colorOrange = Color(0xffF36C3B),
      casesBorderColor = Color(0xFF9875DB),
      casesDivider = Color(0xFFF2EBFF),
      casesStatusBgColor = Color(0xffF5F5F5),
      housingColor = Color(0xffEB2C37),
      dataTableGrey = Color(0xffdee2e6),
      redGenderIconColor = Color(0xffFF5D9E),
      selectedAssessmentBgColor = Color(0xfffaf9fd);
  static Color scaffoldBgColor = Colors.white,
      timelineBorderColor = ColorConstants.primaryColor.withOpacity(0.5),
      cardGreenBackground = const Color(0xffF6FEF8),
      cardBlueBackground = const Color(0xffF6F9FC),
      cardBlueForeground = const Color(0xff0D73CF),
      cardPurpleForeground = const Color(0xff675DC6),
      cardOrangeBackground = const Color(0xffFCF3ED),
      cardOrangeForeground = const Color(0xffF36C3B),
      lightPrimaryColor = const Color(0xff9875DB).withOpacity(0.07);
}
